# Generated by Django 5.0.7 on 2024-08-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255, verbose_name='Название вида работы')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Количество отработанных часов')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Запись о работе',
                'verbose_name_plural': 'Записи о работе',
            },
        ),
    ]
