# Generated by Django 5.0.7 on 2024-08-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workentry',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
